### PR TITLE
refactor(various) code quality, dead code removal, overall cleanup

### PR DESCRIPTION
**Pull request by mgomersbach**
Shellcheck:
 * Add Travis check
 * From 65 errors and 510 warnings to 0
 * 396 security and style improvements

Repair and tested most main profiles
Repair get_kernel_and_initrd and allow fallback kernels
Repair stage_latest
Repair unpack_repo_tree
Fix bug where device is not ready yet

Apply shebang to allow reuse and avoid shell override
Normalize space usage
Normalize line continuation
Strip trailing spaces
Normalize commented code
Make some oneliners more readable
Get rid of perl server and simplify fetch function
Remove binaries from source repo

Signed-off-by: Mark Gomersbach <markgomersbach@gmail.com>

### CODE REVIEW

**Comment by r1k0** [comment]
Hello,
Thanks for your interest and the time you've put into this request.
Give me a little while though, haven't played with gentoo for a long time.
I'll come back here.

**Comment by mgomersbach** [comment]
I am grateful you are even willing to consider such a big commit :D

**Comment by r1k0** [comment]
Thanks a lot for your effort, it's well appreciated.
However, I will put back the daemon and some spaces :).
Also why a shebang on each file if they are sourced from a bash process?

**Comment by mgomersbach** [comment]
The shebang allows various editors, linters and stylecheckers to pick up on the type etc.
It's also a handy reminder for new users that the profiles are just bash scripts.
Sorry about the daemon, now I know it's still used :grin:

**Pull request merged**
